function                                                                     ...
generateKinematicsSolutionsPurposeMessage(  )
%{------------------------------------------------------------------------------
   STDOUT = 1;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   fprintf                                                                   ...
   (                                                                         ...
     STDOUT,                                                                 ...
     [                                                                       ...
       '\n\n\n'                                                              ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n'                                            ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                        ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n'                                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n'                                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                        ...
       '%s%s\n'                                                              ...
       '\n\n\n'                                                              ...
     ],                                                                      ...
     '====================================================================', ...
     '===========',                                                          ...
     '|',                                                                    ...
     '|  FUNCTION:',                                                         ...
     '|',                                                                    ...
     '|    generateSolutionsForFreeRotationRigidBodyKinematics',             ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  PURPOSE:',                                                          ...
     '|',                                                                    ...
     '|    Generate solutions at specified times for torque free',           ...
     '|    rotation of rigid bodies.',                                       ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  INPUTS:',                                                           ...
     '|',                                                                    ...
     '|    J',                                                               ...
     '|      A three by three matrix of double precision floating point',    ...
     '|      Initial Tensor values.',                                        ...
     '|      UNIT(s):  [kilograms/meter squared]',                           ...
     '|',                                                                    ...
     '|    initialScalarFirstUnitQuaternion',                                ...
     '|      A one dimensional vector of four elements containing the',      ...
     '|      initial scalar first unit quaternion.',                         ...
     '|      UNIT(s):  [nondimensional]',                                    ...
     '|',                                                                    ...
     '|    initialAngularVelocity',                                          ...
     '|      A one dimensional vector of length three containing the',       ...
     '|      initial angular velocity vector in non-inertial body',          ...
     '|      coordinates.',                                                  ...
     '|      UNIT(s):  [radians/second]',                                    ...
     '|',                                                                    ...
     '|    numberTimeSamples',                                               ...
     '|      Number of time data points generated for the results.',         ...
     '|      UNIT(s):  [nondimensional]',                                    ...
     '|',                                                                    ...
     '|    simulationEndTime',                                               ...
     '|      Maximum time value for the simulation.',                        ...
     '|      UNIT(s):  [seconds]',                                           ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  OUTPUTS:',                                                          ...
     '|',                                                                    ...
     '|    actualSimuationTimes',                                            ...
     '|      A one dimensional vector the ith element of which is the time', ...
     '|      of the ith simulation time.',                                   ...
     '|      UNIT(s):  [seconds]',                                           ...
     '|',                                                                    ...
     '|    scalarFirstUnitQuaternions',                                      ...
     '|      A two dimensional matrix having four rows and as many',         ...
     '|      columns as there are time samples.',                            ...
     '|      The jth column of this matrix is the scalar first unit',        ...
     '|      quaternion for the jth sample time.',                           ...
     '|      UNIT(s):  [nondimensional]',                                    ...
     '|',                                                                    ...
     '|    angularVelocitiesBodyCoordinates',                                ...
     '|      A one dimensional vector the ith element of which is the',      ...
     '|      angular velocity of the ith sample time in non-inertial',       ...
     '|      body coordinates.',                                             ...
     '|      UNIT(s):  [radians/second]',                                    ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  NOTE(s):',                                                          ...
     '|',                                                                    ...
     '|    [ 1 ]  The input argument list is specified as Matlab "varargin"',...
     '|           so that this function can manage everything about the',    ...
     '|           input argument list.',                                     ...
     '|           If the input argument list was provided explicitly and a', ...
     '|           user provided too many input arguments, then Matlab would',...
     '|           generate an error message and this function''s error',     ...
     '|           handling would never be invoked.',                         ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  REFERENCE(s):',                                                     ...
     '|',                                                                    ...
     '|    [ 1 ]  "The Kinematic Equation for the Rotation Vector",',        ...
     '|           Malcolm D. Shuster,',                                      ...
     '|           IEEE Transactions on Aerospace and Electronic Systems,',   ...
     '|           Vol. 29, No. 1, pp. 263 - 267,',                           ...
     '|           January 1993',                                             ...
     '|           malcolmdshuster.com/Pub_1993c_J_RotVec_IEEE.pdf',          ...
     '|',                                                                    ...
     '|    [ 2 ]  "A Survey of Attitude Representations",',                  ...
     '|           Malcolm D. Shuster,',                                      ...
     '|           The Journal of the Astronautical Sciences,',               ...
     '|           Vol. 41, No. 4, pp. 430 - 517,',                           ...
     '|           October-December, 1993',                                   ...
     '|           malcolmdshuster.com/Pub_1993h_J_Repsurv_scan.pdf',         ...
     '|',                                                                    ...
     '====================================================================', ...
     '==========='                                                           ...
   );
%------------------------------------------------------------------------------- 
   return;
%}------------------------------------------------------------------------------
